mutation($file: Upload!){
  gpxFileInfo(file: $file){
    name
    startDate
    endDate
    distanceKm
    avgSpeedKmPerH
		maxSpeedKmPerH
    movingTime {
      hours
      minutes
    }
    stoppedTime {
      hours
      minutes
    }
    uphillM
    downhillM
  }
}
