query($prefix: ID!) {
    logbook(prefix: $prefix) {
        prefix
        title
        tracks{
            name
            owner {
                name
            }
            photos {
                previewUrl
            }
        }
    }
}
