query($subdomain: ID!) {
    logbook(subdomain: $subdomain) {
        subdomain
        title
        headerImage
        tracks{
            name
            owner {
                name
                profileImage
            }
            photos {
                previewUrl
            }
        }
    }
}
