mutation (
    $name: String,
    $profileImage: Upload,
    $logbookHeaderImage: Upload,
    $logbookTitle: String,
    $logbookSubdomain: String
) {
    userUpdate(
        name: $name,
        logbookTitle: $logbookTitle,
        profileImage: $profileImage,
        logbookHeaderImage: $logbookHeaderImage,
        logbookSubdomain: $logbookSubdomain
    ) {
        id
    }
}
