mutation ($name: String, $profileImage: Upload, $logbookHeaderImage: Upload, $logbookTitle: String) {
    userUpdate(name: $name, logbookTitle: $logbookTitle, profileImage: $profileImage, logbookHeaderImage: $logbookHeaderImage) {
        id
    }
}
