query {
    myStages {
        id
        created
        name
        description
        startDate
        endDate
        coverImage
        distanceKm
        movingTime {
            hours
            minutes
        }
        stoppedTime {
            hours
            minutes
        }
        maxSpeedKmPerH
        avgSpeedKmPerH
        uphillM
        downhillM
        geojsonPreview
    }
}
