query ($id: Int!) {
    tour(id: $id) {
        id
        name
        startDate
        endDate
        description
        coverImage
        owner {
            id
            name
        }
    }
}
