query($id: ID!) {
    track(id: $id) {
        id
        name
        startDate
        endDate
        description
        coverImage
        owner {
            id
            name
        }
        tracks {
            id
            name
            startDate
            endDate
            geojsonPreview
        }
    }
}
