query($id: ID!) {
    track(id: $id) {
        id
        created
        owner {
            id
            name
        }
        name
        description
        startDate
        endDate
        distanceKm
        movingTime {
            hours
            minutes
        }
        stoppedTime {
            hours
            minutes
        }
        maxSpeedKmPerH
        avgSpeedKmPerH
        uphillM
        downhillM
        geojson
    }
}
