mutation(
    $name: String!
    $description: String,
    $tourId: ID
    $startDate: Date!
    $endDate: Date!
    $gpxFile: Upload
    $avgSpeedKmPerH: Float
    $distanceKm: Float
    $downhillM: Float
    $uphillM: Float
    $maxSpeedKmPerH: Float
    $movingTimeHours: Int
    $movingTimeMinutes: Int
    $stoppedTimeHours: Int
    $stoppedTimeMinutes: Int
) {
    trackCreate(
        name: $name,
        description: $description
        tourId: $tourId
        startDate: $startDate
        endDate: $endDate
        gpxFile: $gpxFile
        avgSpeedKmPerH: $avgSpeedKmPerH
        distanceKm: $distanceKm
        downhillM: $downhillM
        uphillM: $uphillM
        maxSpeedKmPerH: $maxSpeedKmPerH
        movingTime: { hours: $movingTimeHours, minutes: $movingTimeMinutes }
        stoppedTime: { hours: $stoppedTimeHours, minutes: $stoppedTimeMinutes }
    ) {
        name
        startDate
        endDate
        distanceKm
        movingTime {
            hours
            minutes
        }
        stoppedTime {
            hours
            minutes
        }
        maxSpeedKmPerH
        avgSpeedKmPerH
        uphillM
        downhillM
    }
}
